- name: Fetch Google apt key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp/apt-key.gpg
    mode: '0440'

- name: Install Google apt key
  ansible.builtin.shell: gpg --dearmour < /tmp/apt-key.gpg > /etc/apt/trusted.gpg.d/cgoogle.gpg
  become: true

- name: Add google repository
  ansible.builtin.shell: apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  become: true

- name: Install k8s binaries
  ansible.builtin.apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - runc
  become: true

- name: Copy k8s configuration file
  ansible.builtin.template:
    src: kubeadm-config.yaml
    dest: /tmp/kubeadm-config.yaml
    mode: '0644'

- name: Initialize cluster
  ansible.builtin.shell: kubeadm init --config=/tmp/kubeadm-config.yaml
  become: true

- name: Install CNI (callico)
  ansible.builtin.shell: "{{item}}"
  with_items:
    - kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true

- name: Mark node as scheduleable
  ansible.builtin.shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true

